baseURL = "/"
languageCode = "ko-kr"
title = "Propaganda for Myself"
themesDir = "themes"
theme = "hugo-serif-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = "G-5DX0LXGKSH"
  google_tag_manager_id = ""

  [params.homepage]
    show_contact_box = true # show / hide the contaxt box on the homepage
    show_services_button = true  # show / hide the "view all services" button

  [params.logo]
    mobile = "images/logo/logo-dark.svg"
    mobile_height = "36px"
    desktop = "images/logo/logo-pfm.svg"
    desktop_height = "36px"
    alt = "Serif - A Hugo Business Theme"

  [params.seo]
    meta_twitter_site = "@propagandafomyself"
    meta_twitter_creator = "@propagandafomyself"

#[params.team]
#summary_large_truncate = 120  # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = 'Copyright © Ajin Im 2021 '

[menu]
  # Main Menu
  [[menu.main]]
    name = "Services"
    url = "/services/"
      weight = 1

  #[[menu.main]]
   #   name = "Team"
    #  url = "/team/"
     # weight = 2

  [[menu.main]]
      name = "About"
      url = "/about/"
      weight = 2

  [[menu.main]]
      name = "Contact"
      url = "/contact/"
      weight = 3

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 2
